task: llm-sft
base_model: TheFinAI/fl-cleveland-sft-1-adapter
project_name: fl-cleveland-sft-2-adapter
log: all
backend: local

wandb:
  run_name: fl-cleveland-sft-2-adapter
  log_model: true
  tags: ["federated-learning", "sft", "cleveland"]

data:
  path: TheFinAI/MED_SYN2_CLEVELAND_train
  train_split: train
  valid_split: null
  chat_template: tokenizer
  column_mapping:
    text_column: entries

params:
  block_size: 256
  model_max_length: 42000
  epochs: 1
  batch_size: 1
  lr: 0.0005
  peft: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0
  quantization: int4
  target_modules: all-linear
  padding: right
  optimizer: adamw_torch
  scheduler: cosine
  gradient_accumulation: 4
  mixed_precision: bf16
  merge_adapter: false

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true
