task: llm-sft
base_model: Qwen/Qwen3-4B-Instruct-2507
project_name: abs-data-sft
log: all
backend: local

wandb:
  run_name: abs-data-sft
  log_model: true
  tags: ["abstract", "data", "xulab"]

data:
  path: clinicalnlplab/ABS_DATA_train
  train_split: train
  valid_split: null
  chat_template: tokenizer
  column_mapping:
    text_column: entries

params:
  block_size: 256
  model_max_length: 42000
  epochs: 50
  batch_size: 8
  lr: 0.0005
  peft: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0
  quantization: int4
  target_modules: all-linear
  padding: right
  optimizer: adamw_torch
  scheduler: cosine
  gradient_accumulation: 4
  mixed_precision: bf16
  merge_adapter: true

hub:
  username: clinicalnlplab
  token: ${HF_TOKEN}
  push_to_hub: true
